### ISSUE TITLE
The action is not working with tflint v0.54.0

### ISSUE THREAD

**Issue by kyontan** [suzuki-shunsuke/github-action-tflint#1144]
tflint v0.54.0 removed `--module` option, and this action specifies `--module` internally, so it fails.

https://github.com/terraform-linters/tflint/releases/tag/v0.54.0

https://github.com/suzuki-shunsuke/github-action-tflint/blob/v1.0.0/src/run.ts#L82-L85

**Comment by suzuki-shunsuke** [comment]
Thank you for reporting this issue.
This issue has already been at main branch, but we need to release a new version.

- https://github.com/suzuki-shunsuke/github-action-tflint/pull/1065

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/github-action-tflint/pull/1145

**Comment by suzuki-shunsuke** [comment]
🎉 https://github.com/suzuki-shunsuke/github-action-tflint/releases/tag/v1.1.1
